name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd server
          npm install --legacy-peer-deps

      - name: Install Frontend Dependencies
        run: |
          cd pdfrag
          npm install --legacy-peer-deps

      - name: Build Frontend
        run: |
          cd pdfrag
          npm run build